name: Build & test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 'Create & configure env file'
              shell: bash
              run: |
                touch .env
                echo "GITHUB_CONTENT_REPOSITORY=Tasker-Rocket/Content" >> .env
                echo "GITHUB_REPOSITORY_IS_PRIVATE=false" >> .env
                echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
                echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
                cat .env

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Run prettier
              run: npm run prettier
        
            - name: Run TypeScript check
              run: npm run tsc
            
            - name: Run E2E & component tests
              uses: cypress-io/github-action@v6
              with:
                start: npm run dev
                
            - name: Upload screenshots of failed tests
              uses: actions/upload-artifact@v4.0.0
              if: failure()
              with:
                name: cypress-screenshots
                path: cypress/screenshots
                retention-days: 1
              
            - name: Run build
              run: npm run build

            - name: 'Remove env file'
              if: always()
              shell: bash
              run: |
                rm .env
